# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Sankaran Vaidyanathan
tagline:          'Personal Webpage'
description:      'sankaranv8@gmail.com'
url:              https://sankaranv.github.io
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Sankaran Vaidyanathan'
  url:            https://sankaranv.github.io

paginate:         1
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

email:              sankaranv8@gmail.com
github:
  repo:             https://github.com/sankaranv
twitter:            https://twitter.com/sankaranv8
linkedin:           https://www.linkedin.com/in/sankaranv8/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
